[package]
name = "wayeyes"
version = "0.1.0"
edition = "2024"
rust-version = "1.87"
description = "xeyes reimagined for Wayland"
license = "MIT"
repository = "https://github.com/Osilvfe/wayeyes"

[dependencies]
anyhow = "1.0"
ashpd = { version = "0.13.13", default-features = false, features = ["screencast", "tokio"] }
clap = { version = "4.5", features = ["derive"] }
gtk = { package = "gtk4", version = "0.10" }
pipewire = "0.10.1"
tokio = { version = "1.51", features = ["rt", "time"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
wayland-client = "0.31.15"
wayland-protocols = { version = "0.32.13", features = ["client", "staging", "unstable"] }

[profile.release]
lto = "thin"
strip = "symbols"
